---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks/

# - Developer:
#     - GitHub:
#         icon: github.png
#         href: https://github.com/
#     - Cloudflare:
#         icon: cloudflare.png
#         href: https://dash.cloudflare.com/
