---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings/

title: Homelab
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, md, lg, xl...
  saturate: 50 # 50, 100, 150...
  brightness: 50 # 50, 100, 150...
  opacity: 50 # 0-100

theme: dark # dark, light

color: slate

layout:
  # specific layout options
  # https://gethomepage.dev/en/configs/layout/
